import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  MessageSquare, 
  FileText, 
  Globe, 
  Upload, 
  Sparkles, 
  ArrowRight, 
  RotateCcw, 
  BarChart3, 
  Target, 
  Lightbulb, 
  CheckCircle2,
  Instagram,
  Facebook,
  Twitter,
  Copy,
  Check,
  Download,
  Share2,
  X,
  TrendingUp,
  Loader2
} from 'lucide-react';
import { SiteAudit } from './components/SiteAudit';
import logoImg from './assets/logo.png';
import { Link, useSearchParams } from 'react-router-dom';
import { GoogleGenAI, Type } from "@google/genai";
// @ts-ignore
import html2pdf from 'html2pdf.js';

type Tab = 'brief' | 'audit';

const TikTokIcon = ({ className }: { className?: string }) => (
  <svg 
    viewBox="0 0 24 24" 
    fill="currentColor" 
    className={className}
    xmlns="http://www.w3.org/2000/svg"
  >
    <path d="M12.525.02c1.31-.02 2.61-.01 3.91-.02.08 1.53.63 3.09 1.75 4.17 1.12 1.11 2.7 1.62 4.24 1.79v4.03c-1.44-.17-2.86-.6-4.12-1.31a6.38 6.38 0 0 1-1.87-1.5c-.02 3.14-.03 6.28-.04 9.42-.01 1.05-.09 2.1-.44 3.1-.58 1.73-2.02 3.18-3.72 3.79-1.7.61-3.62.54-5.26-.25-1.64-.79-2.92-2.36-3.41-4.12-.49-1.75-.22-3.68.75-5.23.97-1.55 2.59-2.62 4.4-2.81.18-.02.36-.03.54-.03v4.09c-.31.03-.63.08-.93.17-1.14.34-2.02 1.41-2.14 2.6-.12 1.19.46 2.41 1.45 3.07.99.66 2.32.74 3.4.2.98-.49 1.63-1.54 1.75-2.62.12-1.12.11-2.24.11-3.36V.02z"/>
  </svg>
);

export default function AdStudio() {
  const [searchParams] = useSearchParams();
  const initialTab = (searchParams.get('tab') as Tab) || 'brief';
  const [activeTab, setActiveTab] = useState<Tab>(initialTab);
  
  useEffect(() => {
    const tab = searchParams.get('tab') as Tab;
    if (tab && ['brief', 'audit'].includes(tab)) {
      setActiveTab(tab);
    }
  }, [searchParams]);
  const [briefStep, setBriefStep] = useState<'upload' | 'analyzing' | 'results'>('upload');
  const [selectedImage, setSelectedImage] = useState<string | null>(null);
  const [analysisProgress, setAnalysisProgress] = useState(0);
  const [resultsTab, setResultsTab] = useState<'insights' | 'concepts'>('insights');
  const [generatedImages, setGeneratedImages] = useState<Record<number, string>>({});
  const [generatingIndices, setGeneratingIndices] = useState<Set<number>>(new Set());
  const [briefData, setBriefData] = useState<any>(null);
  const [isDownloading, setIsDownloading] = useState(false);
  const reportRef = useRef<HTMLDivElement>(null);

  const generateAdImage = async (index: number, ad: any) => {
    if (generatingIndices.has(index) || !briefData) return;
    
    setGeneratingIndices(prev => new Set(prev).add(index));
    try {
      const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || '' });

      const prompt = `Professional product advertisement image for: ${ad.headline}. 
      Context: ${ad.body}. 
      Visual Style: ${briefData.visualPrompt}. 
      The image should be a close visual match to the original product photo but optimized for ${ad.platform}. 
      High-end commercial photography, 8k resolution, vibrant lighting.`;

      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [
            {
              text: prompt,
            },
          ],
        },
        config: {
          imageConfig: {
            aspectRatio: "1:1"
          }
        }
      });

      let imageUrl = '';
      if (response.candidates?.[0]?.content?.parts) {
        for (const part of response.candidates[0].content.parts) {
          if (part.inlineData) {
            imageUrl = `data:image/png;base64,${part.inlineData.data}`;
            break;
          }
        }
      }

      if (!imageUrl) {
        throw new Error("No image was generated by the model.");
      }
      
      setGeneratedImages(prev => ({ ...prev, [index]: imageUrl }));
    } catch (error: any) {
      console.error("Error generating image:", error);
      alert(`Image generation failed: ${error.message}`);
    } finally {
      setGeneratingIndices(prev => {
        const next = new Set(prev);
        next.delete(index);
        return next;
      });
    }
  };

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (event) => {
        setSelectedImage(event.target?.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const startAnalysis = async () => {
    if (!selectedImage) return;
    
    setBriefStep('analyzing');
    setAnalysisProgress(10);
    
    try {
      const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || '' });
      
      // Extract base64 data
      const base64Data = selectedImage.split(',')[1];
      
      setAnalysisProgress(30);
      
      const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: [
          {
            parts: [
              {
                inlineData: {
                  mimeType: "image/jpeg",
                  data: base64Data
                }
              },
              {
                text: `Analyze this product image and provide a comprehensive marketing brief. 
                Return the result in strict JSON format with the following structure:
                {
                  "productAnalysis": "A detailed 2-3 sentence description of the product based on the image.",
                  "visualPrompt": "A highly detailed visual description of the product, its packaging, colors, textures, and lighting as seen in the image. This will be used as a prompt to generate similar images, so be extremely specific about the visual details to ensure a close match.",
                  "targetAudience": ["Audience 1", "Audience 2", "Audience 3"],
                  "marketInsights": ["Insight 1", "Insight 2"],
                  "competitiveAdvantages": ["Advantage 1", "Advantage 2"],
                  "adConcepts": [
                    { "platform": "Instagram", "headline": "Catchy headline", "body": "Persuasive ad copy", "cta": "Shop Now" },
                    { "platform": "Facebook", "headline": "Catchy headline", "body": "Persuasive ad copy", "cta": "Learn More" },
                    { "platform": "TikTok", "headline": "Catchy headline", "body": "Persuasive ad copy", "cta": "Get Started" }
                  ]
                }`
              }
            ]
          }
        ],
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              productAnalysis: { type: Type.STRING },
              visualPrompt: { type: Type.STRING },
              targetAudience: { type: Type.ARRAY, items: { type: Type.STRING } },
              marketInsights: { type: Type.ARRAY, items: { type: Type.STRING } },
              competitiveAdvantages: { type: Type.ARRAY, items: { type: Type.STRING } },
              adConcepts: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    platform: { type: Type.STRING },
                    headline: { type: Type.STRING },
                    body: { type: Type.STRING },
                    cta: { type: Type.STRING }
                  },
                  required: ["platform", "headline", "body", "cta"]
                }
              }
            },
            required: ["productAnalysis", "visualPrompt", "targetAudience", "marketInsights", "competitiveAdvantages", "adConcepts"]
          }
        }
      });

      setAnalysisProgress(80);
      
      const data = JSON.parse(response.text);
      setBriefData(data);
      
      setAnalysisProgress(100);
      setTimeout(() => setBriefStep('results'), 500);
      
    } catch (error) {
      console.error("Analysis failed:", error);
      setBriefStep('upload');
    }
  };

  const [kieTestResult, setKieTestResult] = useState<{status: string, message: string} | null>(null);
  const [isTestingKie, setIsTestingKie] = useState(false);

  const handleDownload = async () => {
    if (!reportRef.current || !briefData) return;
    
    setIsDownloading(true);
    try {
      const element = reportRef.current;
      const opt = {
        margin: [10, 10] as [number, number],
        filename: `Ad-Brief-${briefData.productAnalysis?.substring(0, 20).replace(/\s+/g, '-') || 'report'}.pdf`,
        image: { type: 'jpeg' as const, quality: 0.98 },
        html2canvas: { 
          scale: 2, 
          useCORS: true,
          logging: false,
          backgroundColor: '#121417',
          onclone: (clonedDoc: Document) => {
            // Remove oklch color functions which html2canvas doesn't support
            const elements = clonedDoc.getElementsByTagName('*');
            for (let i = 0; i < elements.length; i++) {
              const el = elements[i] as HTMLElement;
              const style = window.getComputedStyle(el);
              
              ['color', 'backgroundColor', 'borderColor'].forEach(prop => {
                const val = (el.style as any)[prop] || style.getPropertyValue(prop);
                if (val && val.includes('oklch')) {
                  if (prop === 'color') el.style.color = '#ffffff';
                  if (prop === 'backgroundColor') el.style.backgroundColor = 'transparent';
                  if (prop === 'borderColor') el.style.borderColor = '#333333';
                }
              });
            }
          }
        },
        jsPDF: { unit: 'mm' as const, format: 'a4' as const, orientation: 'portrait' as const }
      };

      await html2pdf().set(opt).from(element).save();
    } catch (err) {
      console.error("Failed to generate PDF", err);
      alert("PDF generation failed. Opening print dialog as a fallback...");
      window.print();
    } finally {
      setIsDownloading(false);
    }
  };
  const testKieConnection = async () => {
    setIsTestingKie(true);
    setKieTestResult(null);
    try {
      const kieApiKey = process.env.KIE_API_KEY;
      if (!kieApiKey) {
        throw new Error("KIE_API_KEY is missing in environment variables");
      }

      const response = await fetch('https://api.kie.ai/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${kieApiKey}`
        },
        body: JSON.stringify({
          model: 'gpt-4o',
          messages: [
            { role: 'user', content: 'Say "Kie.ai connection successful!"' }
          ],
          max_tokens: 20
        })
      });

      if (!response.ok) {
        let errorMessage = `Status ${response.status}`;
        try {
          const errorData = await response.json();
          errorMessage += `: ${errorData.error?.message || errorData.message || JSON.stringify(errorData)}`;
        } catch (e) {
          const text = await response.text().catch(() => '');
          if (text) errorMessage += `: ${text.substring(0, 200)}`;
        }
        throw new Error(`Kie.ai API failed: ${errorMessage}`);
      }

      const data = await response.json();
      setKieTestResult({
        status: 'success',
        message: data.choices[0].message.content
      });
    } catch (error: any) {
      setKieTestResult({
        status: 'error',
        message: error.message
      });
    } finally {
      setIsTestingKie(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#121417] text-white font-sans selection:bg-primary/30">
      {/* Kie Test Overlay */}
      {kieTestResult && (
        <div className="fixed top-24 right-4 z-[100] bg-[#1C1F26] border border-white/10 p-4 rounded-2xl shadow-2xl max-w-xs animate-in fade-in slide-in-from-right-4">
          <div className="flex items-center justify-between mb-2">
            <span className={`text-xs font-bold uppercase tracking-widest ${kieTestResult.status === 'success' ? 'text-green-500' : 'text-red-500'}`}>
              Kie.ai Test {kieTestResult.status}
            </span>
            <button onClick={() => setKieTestResult(null)} className="text-white/40 hover:text-white">
              <X className="w-4 h-4" />
            </button>
          </div>
          <p className="text-sm text-white/60">{kieTestResult.message}</p>
        </div>
      )}

      {/* Top Navigation */}
      <div className="fixed top-0 left-0 w-full z-50 px-4 py-6">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2">
            <img src={logoImg} alt="AdHello" className="h-8 w-auto brightness-0 invert" />
          </Link>

          <div className="flex items-center gap-4">
            <button 
              onClick={testKieConnection}
              disabled={isTestingKie}
              className="text-[10px] font-black uppercase tracking-widest text-white/20 hover:text-primary transition-colors disabled:opacity-50"
            >
              {isTestingKie ? 'Testing Kie...' : 'Test Kie Connection'}
            </button>

            <div className="bg-[#1C1F26] p-1 rounded-full flex items-center border border-white/5 shadow-2xl">
            <button
              onClick={() => setActiveTab('brief')}
              className={`flex items-center gap-2 px-6 py-2 rounded-full text-sm font-bold transition-all ${
                activeTab === 'brief' ? 'bg-[#2D323D] text-white shadow-lg' : 'text-white/40 hover:text-white/60'
              }`}
            >
              <FileText className="w-4 h-4" />
              Ad Brief
            </button>
            <button
              onClick={() => setActiveTab('audit')}
              className={`flex items-center gap-2 px-6 py-2 rounded-full text-sm font-bold transition-all ${
                activeTab === 'audit' ? 'bg-[#2D323D] text-white shadow-lg' : 'text-white/40 hover:text-white/60'
              }`}
            >
              <Globe className="w-4 h-4" />
              Site Audit
            </button>
          </div>
        </div>

        <div className="w-24"></div> {/* Spacer for balance */}
      </div>
    </div>

      <main className="pt-32 pb-20 px-4">
        <div className="max-w-7xl mx-auto">
          <AnimatePresence mode="wait">
            {activeTab === 'brief' && (
              <motion.div
                key="brief"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -20 }}
                className="w-full"
              >
                {briefStep === 'upload' && (
                  <div className="max-w-4xl mx-auto text-center">
                    <h1 className="text-5xl md:text-7xl font-extrabold mb-6 text-[#F3DD6D]">
                      Launch Your Ad Strategy in Seconds
                    </h1>
                    <p className="text-xl text-white/60 mb-12 max-w-2xl mx-auto">
                      Upload one photo and let our AI build your complete market brief, target audiences, and platform-ready ad creatives.
                    </p>

                    <div className="relative group">
                      <div className="absolute -inset-1 bg-gradient-to-r from-primary/50 to-yellow-500/50 rounded-[2.5rem] blur opacity-25 group-hover:opacity-50 transition duration-1000 group-hover:duration-200"></div>
                      <div className="relative bg-[#1C1F26] border-2 border-dashed border-white/10 rounded-[2.5rem] p-12 transition-all hover:border-primary/50">
                        {selectedImage ? (
                          <div className="relative inline-block">
                            <img src={selectedImage} alt="Preview" className="max-h-[400px] rounded-2xl shadow-2xl" />
                            <button 
                              onClick={() => setSelectedImage(null)}
                              className="absolute -top-4 -right-4 bg-red-500 p-2 rounded-full shadow-xl hover:bg-red-600 transition-colors"
                            >
                              <X className="w-4 h-4" />
                            </button>
                          </div>
                        ) : (
                          <label className="cursor-pointer flex flex-col items-center">
                            <div className="w-20 h-20 bg-white/5 rounded-full flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
                              <Upload className="w-10 h-10 text-primary" />
                            </div>
                            <span className="text-2xl font-bold mb-2">Drop your product photo here</span>
                            <span className="text-white/40">or click to browse files</span>
                            <input type="file" className="hidden" onChange={handleImageUpload} accept="image/*" />
                          </label>
                        )}
                      </div>
                    </div>

                    {selectedImage && (
                      <motion.button
                        initial={{ opacity: 0, scale: 0.9 }}
                        animate={{ opacity: 1, scale: 1 }}
                        onClick={startAnalysis}
                        className="mt-10 bg-primary hover:bg-primary-hover text-brand-dark px-10 py-5 rounded-full font-black text-xl flex items-center gap-3 mx-auto transition-all hover:scale-105 shadow-2xl shadow-primary/20"
                      >
                        <Sparkles className="w-6 h-6" />
                        Analyze & Generate Ads
                        <ArrowRight className="w-6 h-6" />
                      </motion.button>
                    )}

                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-20">
                      <div className="bg-[#1C1F26] p-8 rounded-3xl border border-white/5 text-left">
                        <div className="w-12 h-12 bg-primary/10 rounded-xl flex items-center justify-center mb-6">
                          <Target className="w-6 h-6 text-primary" />
                        </div>
                        <h4 className="text-xl font-bold mb-2">Market Analysis</h4>
                        <p className="text-white/40">Identify target audiences and positioning</p>
                      </div>
                      <div className="bg-[#1C1F26] p-8 rounded-3xl border border-white/5 text-left">
                        <div className="w-12 h-12 bg-primary/10 rounded-xl flex items-center justify-center mb-6">
                          <BarChart3 className="w-6 h-6 text-primary" />
                        </div>
                        <h4 className="text-xl font-bold mb-2">Competitive Insights</h4>
                        <p className="text-white/40">Discover your unique advantages</p>
                      </div>
                      <div className="bg-[#1C1F26] p-8 rounded-3xl border border-white/5 text-left">
                        <div className="w-12 h-12 bg-primary/10 rounded-xl flex items-center justify-center mb-6">
                          <Sparkles className="w-6 h-6 text-primary" />
                        </div>
                        <h4 className="text-xl font-bold mb-2">Ready-to-Use Ads</h4>
                        <p className="text-white/40">Generate platform-specific ad creatives</p>
                      </div>
                    </div>
                  </div>
                )}

                {briefStep === 'analyzing' && (
                  <div className="max-w-2xl mx-auto text-center py-20">
                    <div className="relative w-48 h-48 mx-auto mb-12">
                      <div className="absolute inset-0 border-4 border-white/5 rounded-full"></div>
                      <svg className="absolute inset-0 w-full h-full transform -rotate-90" viewBox="0 0 100 100">
                        <circle
                          className="text-primary stroke-current transition-all duration-300"
                          strokeWidth="4"
                          strokeLinecap="round"
                          cx="50"
                          cy="50"
                          r="48"
                          fill="transparent"
                          strokeDasharray={`${analysisProgress * 3.0159} 301.59`}
                        ></circle>
                      </svg>
                      <div className="absolute inset-0 flex items-center justify-center">
                        <div className="w-32 h-32 bg-[#1C1F26] rounded-full flex items-center justify-center shadow-2xl">
                          <Sparkles className="w-12 h-12 text-primary animate-pulse" />
                        </div>
                      </div>
                    </div>

                    <h2 className="text-4xl font-extrabold mb-4">Analyzing your product...</h2>
                    <p className="text-white/60 text-xl mb-12">Our AI is studying your image to create the perfect ads</p>

                    <div className="space-y-4 max-w-sm mx-auto">
                      <div className="flex items-center gap-3 text-left">
                        {analysisProgress > 30 ? <CheckCircle2 className="w-5 h-5 text-green-500" /> : <div className="w-5 h-5 rounded-full border-2 border-white/10 animate-spin border-t-primary"></div>}
                        <span className={analysisProgress > 30 ? 'text-white' : 'text-white/40'}>Identifying product features</span>
                      </div>
                      <div className="flex items-center gap-3 text-left">
                        {analysisProgress > 60 ? <CheckCircle2 className="w-5 h-5 text-green-500" /> : <div className="w-5 h-5 rounded-full border-2 border-white/10 animate-spin border-t-primary"></div>}
                        <span className={analysisProgress > 60 ? 'text-white' : 'text-white/40'}>Analyzing market positioning</span>
                      </div>
                      <div className="flex items-center gap-3 text-left">
                        {analysisProgress > 90 ? <CheckCircle2 className="w-5 h-5 text-green-500" /> : <div className="w-5 h-5 rounded-full border-2 border-white/10 animate-spin border-t-primary"></div>}
                        <span className={analysisProgress > 90 ? 'text-white' : 'text-white/40'}>Generating ad concepts</span>
                      </div>
                    </div>
                  </div>
                )}

                {briefStep === 'results' && (
                  <div ref={reportRef} className="space-y-12">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-4">
                        <div className="w-16 h-16 bg-primary/10 rounded-2xl flex items-center justify-center">
                          <img src={selectedImage || ''} alt="Product" className="w-12 h-12 object-cover rounded-lg" />
                        </div>
                        <div>
                          <h2 className="text-3xl font-extrabold">Your Ad Test Results</h2>
                          <p className="text-white/40">Market research and ad concepts for your product</p>
                        </div>
                      </div>
                      <div className="flex items-center gap-4">
                        <button
                          onClick={handleDownload}
                          disabled={isDownloading}
                          className="flex items-center gap-2 text-sm font-bold px-4 py-2 rounded-full border border-white/10 bg-white/5 text-white/60 hover:text-primary shadow-sm transition-all disabled:opacity-50"
                        >
                          {isDownloading ? (
                            <Loader2 className="w-4 h-4 animate-spin" />
                          ) : (
                            <Download className="w-4 h-4" />
                          )}
                          {isDownloading ? 'Generating...' : 'Download Report'}
                        </button>
                        <button 
                          onClick={() => setBriefStep('upload')}
                          className="flex items-center gap-2 text-white/60 hover:text-white transition-colors font-bold"
                        >
                          <RotateCcw className="w-5 h-5" />
                          Start Over
                        </button>
                      </div>
                    </div>

                    <div className="flex items-center gap-2 bg-[#1C1F26] p-1 rounded-2xl w-fit border border-white/5">
                      <button 
                        onClick={() => setResultsTab('insights')}
                        className={`flex items-center gap-2 px-6 py-2 rounded-xl text-sm font-bold transition-all ${
                          resultsTab === 'insights' ? 'bg-[#2D323D] text-white shadow-lg' : 'text-white/40 hover:text-white/60'
                        }`}
                      >
                        <BarChart3 className="w-4 h-4" />
                        Market Insights
                      </button>
                      <button 
                        onClick={() => setResultsTab('concepts')}
                        className={`flex items-center gap-2 px-6 py-2 rounded-xl text-sm font-bold transition-all ${
                          resultsTab === 'concepts' ? 'bg-[#2D323D] text-white shadow-lg' : 'text-white/40 hover:text-white/60'
                        }`}
                      >
                        <Sparkles className="w-4 h-4" />
                        Ad Concepts (3)
                      </button>
                    </div>

                    <AnimatePresence mode="wait">
                      {resultsTab === 'insights' ? (
                        <motion.div
                          key="insights"
                          initial={{ opacity: 0, y: 10 }}
                          animate={{ opacity: 1, y: 0 }}
                          exit={{ opacity: 0, y: -10 }}
                          className="space-y-8"
                        >
                          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                            <div className="bg-[#1C1F26] p-10 rounded-[2.5rem] border border-white/5">
                              <div className="flex items-center gap-3 mb-6">
                                <FileText className="w-6 h-6 text-primary" />
                                <h3 className="text-2xl font-bold">Product Analysis</h3>
                              </div>
                              <p className="text-white/60 text-lg leading-relaxed">
                                {briefData?.productAnalysis}
                              </p>
                            </div>

                            <div className="bg-[#1C1F26] p-10 rounded-[2.5rem] border border-white/5">
                              <div className="flex items-center gap-3 mb-6">
                                <Target className="w-6 h-6 text-primary" />
                                <h3 className="text-2xl font-bold">Target Audience</h3>
                              </div>
                              <ul className="space-y-4">
                                {briefData?.targetAudience.map((item: string, i: number) => (
                                  <li key={i} className="flex items-start gap-3">
                                    <CheckCircle2 className="w-5 h-5 text-green-500 shrink-0 mt-1" />
                                    <span className="text-white/60">{item}</span>
                                  </li>
                                ))}
                              </ul>
                            </div>

                            <div className="bg-[#1C1F26] p-10 rounded-[2.5rem] border border-white/5">
                              <div className="flex items-center gap-3 mb-6">
                                <Lightbulb className="w-6 h-6 text-primary" />
                                <h3 className="text-2xl font-bold">Market Insights</h3>
                              </div>
                              <ul className="space-y-4">
                                {briefData?.marketInsights.map((item: string, i: number) => (
                                  <li key={i} className="flex items-start gap-3">
                                    <TrendingUp className="w-5 h-5 text-primary shrink-0 mt-1" />
                                    <span className="text-white/60">{item}</span>
                                  </li>
                                ))}
                              </ul>
                            </div>

                            <div className="bg-[#1C1F26] p-10 rounded-[2.5rem] border border-white/5">
                              <div className="flex items-center gap-3 mb-6">
                                <Sparkles className="w-6 h-6 text-primary" />
                                <h3 className="text-2xl font-bold">Competitive Advantages</h3>
                              </div>
                              <ul className="space-y-4">
                                {briefData?.competitiveAdvantages.map((item: string, i: number) => (
                                  <li key={i} className="flex items-start gap-3">
                                    <CheckCircle2 className="w-5 h-5 text-green-500 shrink-0 mt-1" />
                                    <span className="text-white/60">{item}</span>
                                  </li>
                                ))}
                              </ul>
                            </div>
                          </div>

                          <div className="bg-[#1C1F26] p-10 rounded-[2.5rem] border border-white/5">
                            <h3 className="text-2xl font-bold mb-6 flex items-center gap-3">
                              <BarChart3 className="w-6 h-6 text-primary" />
                              Recommended Platforms
                            </h3>
                            <div className="flex flex-wrap gap-4">
                              {['Instagram', 'Facebook', 'TikTok'].map((platform) => (
                                <div key={platform} className="bg-[#121417] px-6 py-3 rounded-2xl border border-white/5 font-bold text-primary">
                                  {platform}
                                </div>
                              ))}
                            </div>
                          </div>
                        </motion.div>
                      ) : (
                        <motion.div
                          key="concepts"
                          initial={{ opacity: 0, y: 10 }}
                          animate={{ opacity: 1, y: 0 }}
                          exit={{ opacity: 0, y: -10 }}
                          className="bg-[#1C1F26] p-10 rounded-[2.5rem] border border-white/5"
                        >
                          <h3 className="text-2xl font-bold mb-8">Ad Concepts</h3>
                          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                            {briefData?.adConcepts.map((ad: any, i: number) => (
                              <div key={i} className="bg-[#121417] rounded-3xl overflow-hidden border border-white/5 flex flex-col">
                                <div className="aspect-square bg-white/5 flex items-center justify-center relative group">
                                  <img 
                                    src={generatedImages[i] || selectedImage || ''} 
                                    alt="Ad" 
                                    className={`w-full h-full object-cover transition-opacity duration-500 ${generatedImages[i] ? 'opacity-100' : 'opacity-50'}`} 
                                  />
                                  <button 
                                    onClick={() => generateAdImage(i, ad)}
                                    disabled={generatingIndices.has(i)}
                                    className="absolute bg-primary text-brand-dark px-6 py-3 rounded-full font-bold flex items-center gap-2 transform transition-transform group-hover:scale-105 disabled:opacity-50 disabled:scale-100"
                                  >
                                    {generatingIndices.has(i) ? (
                                      <Loader2 className="w-4 h-4 animate-spin" />
                                    ) : (
                                      <Sparkles className="w-4 h-4" />
                                    )}
                                    {generatingIndices.has(i) ? 'Generating...' : 'Generate Image'}
                                  </button>
                                </div>
                                <div className="p-6 flex-grow flex flex-col">
                                  <div className="flex items-center gap-2 text-primary text-xs font-black uppercase tracking-widest mb-4">
                                    {ad.platform === 'Instagram' ? <Instagram className="w-5 h-5" /> : ad.platform === 'Facebook' ? <Facebook className="w-5 h-5" /> : <TikTokIcon className="w-5 h-5" />}
                                    {ad.platform}
                                  </div>
                                  <h4 className="text-xl font-bold mb-2">{ad.headline}</h4>
                                  <p className="text-white/40 text-sm mb-6 flex-grow">{ad.body}</p>
                                  <div className="flex items-center gap-2">
                                    <button className="flex-grow bg-primary hover:bg-primary-hover text-brand-dark px-4 py-2 rounded-xl text-sm font-bold transition-colors flex items-center justify-center gap-2">
                                      {ad.platform === 'Instagram' ? 'Shop Now' : ad.platform === 'Facebook' ? 'Learn More' : 'Get Started'}
                                    </button>
                                    <button className="flex items-center gap-2 bg-white/5 hover:bg-white/10 text-white px-4 py-2 rounded-xl text-sm font-bold transition-colors">
                                      <Copy className="w-4 h-4" />
                                      Copy Text
                                    </button>
                                  </div>
                                </div>
                              </div>
                            ))}
                          </div>
                        </motion.div>
                      )}
                    </AnimatePresence>

                    <div className="text-center py-12">
                      <h3 className="text-3xl font-extrabold mb-4">Ready to create more?</h3>
                      <p className="text-white/40 mb-8">Start your 7-day free trial to unlock unlimited ad generation and save your work</p>
                      <button 
                        onClick={() => window.open('https://calendar.app.google/QQsVbiAt4QdCX8mx8', '_blank')}
                        className="bg-primary hover:bg-primary-hover text-brand-dark px-10 py-5 rounded-full font-black text-xl transition-all hover:scale-105"
                      >
                        Start 7-Day Free Trial
                      </button>
                    </div>
                  </div>
                )}
              </motion.div>
            )}

            {activeTab === 'audit' && (
              <motion.div
                key="audit"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="w-full"
              >
                <SiteAudit isStudio={true} />
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </main>
    </div>
  );
}
